name: Issue Recorder
description: Save all comments on an issue to a file in your repository
author: noraworld
branding:
  icon: circle
  color: purple

inputs:
  mode:
    description: mode
    required: false
    default: file
  filepath:
    description: filepath
    required: false
    default: default
  committer_name:
    description: committer name
    required: false
    default: GitHub Actions
  committer_email:
    description: committer email
    required: false
    default: actions@github.com
  overwrite_when_modified:
    description: overwrite when modified
    required: false
    default: ""
  extra_text_when_modified:
    description: extra text when modified
    required: false
    default: "# From issues"
  notification_comment:
    description: notification comment
    required: false
    default: ""
  target_file_repo:
    description: target file repo
    required: false
    default: ""
  title_prefix_for_file:
    description: title prefix for file
    required: false
    default: ""
  target_issue_repo:
    description: target issue repo
    required: false
    default: ""
  target_issue_number:
    description: target issue number
    required: false
    default: ""
  partial_content_target_issue_repo:
    description: partial content target issue repo
    required: false
    default: ""
  partial_content_target_issue_number:
    description: partial content target issue number
    required: false
    default: ""
  partial_content_start_string:
    description: partial content start string
    required: false
    default: ""
  partial_content_end_string:
    description: partial content end string
    required: false
    default: ""
  with_repo_assets:
    description: with repo assets
    required: false
    default: ""
  assets_repo:
    description: assets repo
    required: false
    default: ""
  assets_directory:
    description: assets directory
    required: false
    default: ""
  with_assets_compression:
    description: with assets compression
    required: false
    default: ""
  compression_threshold:
    description: compression threshold
    required: false
    default: ""
  resize_width:
    description: resize width
    required: false
    default: ""
  resize_height:
    description: resize height
    required: false
    default: ""
  with_compatible_format:
    description: with compatible format
    required: false
    default: ""
  fold_threshold:
    description: fold threshold
    required: false
    default: infinity
  fold_summary:
    description: fold summary
    required: false
    default: ""
  title_prefix_for_issue:
    description: title prefix for issue
    required: false
    default: ""
  with_date:
    description: with date
    required: false
    default: ""
  timezone:
    description: timezone
    required: false
    default: Etc/GMT
  time_format:
    description: time format
    required: false
    default: MMM d, yyyy, h:mm a ZZZZ
  with_header:
    description: with header
    required: false
    default: ""
  with_title:
    description: with title
    required: false
    default: ""
  custom_title:
    description: custom title
    required: false
    default: ""
  with_quote:
    description: with quote
    required: false
    default: ""
  with_hr:
    description: with hr
    required: false
    default: "file, issue"
  skip_body:
    description: skip body
    required: false
    default: ""
  skip_if_empty_including_body:
    description: skip if empty including body
    required: false
    default: ""
  skip_if_empty_not_including_body:
    description: skip if empty not including body
    required: false
    default: ""
  fail_if_skip:
    description: fail if skip
    required: false
    default: ""
  personal_access_token:
    description: personal access token
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '21.6.2'

    - name: Install packages
      run: npm install
      shell: sh
      working-directory: ${{ github.action_path }}

    - name: Track issues
      run: node ${{ github.action_path }}/app.js
      shell: sh
      env:
        GITHUB_TOKEN: ${{ github.token }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        ISSUE_TITLE: ${{ github.event.issue.title }}
        ISSUE_BODY: ${{ github.event.issue.body }}
        ISSUE_ASSIGNEES: ${{ toJson(github.event.issue.assignees.*.login) }}
        ISSUE_LABELS: ${{ toJson(github.event.issue.labels.*.name) }}
        ISSUE_URL: ${{ github.event.issue.html_url }}
        ISSUE_CREATED_AT: ${{ github.event.issue.created_at }}
        MODE: ${{ inputs.mode }}
        FILEPATH: ${{ inputs.filepath }}
        COMMITTER_NAME: ${{ inputs.committer_name }}
        COMMITTER_EMAIL: ${{ inputs.committer_email }}
        OVERWRITE_WHEN_MODIFIED: ${{ inputs.overwrite_when_modified }}
        EXTRA_TEXT_WHEN_MODIFIED: ${{ inputs.extra_text_when_modified }}
        NOTIFICATION_COMMENT: ${{ inputs.notification_comment }}
        TARGET_FILE_REPO: ${{ inputs.TARGET_FILE_REPO }}
        TITLE_PREFIX_FOR_FILE: ${{ inputs.title_prefix_for_file }}
        TARGET_ISSUE_REPO: ${{ inputs.target_issue_repo }}
        TARGET_ISSUE_NUMBER: ${{ inputs.target_issue_number }}
        PARTIAL_CONTENT_TARGET_ISSUE_REPO: ${{ inputs.partial_content_target_issue_repo }}
        PARTIAL_CONTENT_TARGET_ISSUE_NUMBER: ${{ inputs.partial_content_target_issue_number }}
        PARTIAL_CONTENT_START_STRING: ${{ inputs.partial_content_start_string }}
        PARTIAL_CONTENT_END_STRING: ${{ inputs.partial_content_end_string }}
        WITH_REPO_ASSETS: ${{ inputs.with_repo_assets }}
        ASSETS_REPO: ${{ inputs.assets_repo }}
        ASSETS_DIRECTORY: ${{ inputs.assets_directory }}
        WITH_ASSETS_COMPRESSION: ${{ inputs.with_assets_compression }}
        COMPRESSION_THRESHOLD: ${{ inputs.compression_threshold }}
        RESIZE_WIDTH: ${{ inputs.resize_width }}
        RESIZE_HEIGHT: ${{ inputs.resize_height }}
        WITH_COMPATIBLE_FORMAT: ${{ inputs.with_compatible_format }}
        FOLD_THRESHOLD: ${{ inputs.fold_threshold }}
        FOLD_SUMMARY: ${{ inputs.fold_summary }}
        TITLE_PREFIX_FOR_ISSUE: ${{ inputs.title_prefix_for_issue }}
        WITH_DATE: ${{ inputs.with_date }}
        TIMEZONE: ${{ inputs.timezone }}
        TIME_FORMAT: ${{ inputs.time_format }}
        WITH_HEADER: ${{ inputs.with_header }}
        WITH_TITLE: ${{ inputs.with_title }}
        CUSTOM_TITLE: ${{ inputs.custom_title }}
        WITH_QUOTE: ${{ inputs.with_quote }}
        WITH_HR: ${{ inputs.with_hr }}
        SKIP_BODY: ${{ inputs.skip_body }}
        SKIP_IF_EMPTY_INCLUDING_BODY: ${{ inputs.skip_if_empty_including_body }}
        SKIP_IF_EMPTY_NOT_INCLUDING_BODY: ${{ inputs.skip_if_empty_not_including_body }}
        FAIL_IF_SKIP: ${{ inputs.fail_if_skip }}
        PERSONAL_ACCESS_TOKEN: ${{ inputs.personal_access_token }}
